#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 1
bspc config bottom_padding 19
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

bspc config normal_border_color '#3b3b3b'
bspc config active_border_color '#d8ad4c'
bspc config focused_border_color '#d8ad4c'
