# Enable color support of ls and also add handy aliases.
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls
alias ls='ls --color=auto -CF'
alias la='ls --color=auto -ACF'
alias ll='ls --color=auto -alF'

# cd into the git repository's root path.
alias cdgit='cd `git rev-parse --show-toplevel`'

# sxiv
alias sxiv='sxiv -qr'

# xclip
alias xpaste='xclip -o -sel c'
alias xcopy='xclip -sel c'

# daily-thought
alias dl='daily-thought.py --work-dir ~/dailythoughts-data/'

# cd into a directory found by fzf
cdfzf() {
    dir=$(find . -type d | fzf)
    [ $? -eq 0 ] && cd "$dir"
}

# replace cd with zoxide
eval "$(zoxide init --cmd cd bash)"
